### ISSUE TITLE
Is image reslicing needed before extracting visual words?

### ISSUE THREAD

**Issue by mkvasnytsia** [fhaghighi/SemanticGenesis#5]
Dear authors,
Thank you for sharing your code.
I am wondering if you expect the input images to be resized/resliced  to one predefined size prior to running pattern_generator_3D.py  in the self-discovery phase of pre-training?

**Comment by fhaghighi** [comment]
Hi, Thanks for your interest in our work. Yes, we resize them to the same size before extracting visual words.

**Comment by mkvasnytsia** [comment]
Thanks for such a quick answer!
